### ISSUE TITLE
Cannot import torch-spline-conv when installed from pip wheel in Torch 1.9.0

### ISSUE THREAD

**Issue by saiden89** [rusty1s/pytorch_spline_conv#22] opened 2021-06-23 17:31 UTC
As discussed [here](https://github.com/rusty1s/pytorch_geometric/issues/2744), installing `torch-spline-conv` via the provided wheels fails with `OSError: /lib64/libm.so.6: version 'GLIBC_2.27' not found` . 
We know that:

- the issue is unaffected by the `cudatoolkit` version
- the issue is unaffected by `python` version
- the issue triggers only with `torch 1.9.0`
- the issue triggers only on systems with CUDA acceleration.
- recompiling solves the issue

As per @rusty1s suggestion, adding a `print` statement in `torch_spline_conv/__init__.py` between lines 10 and 11, produces the following output:
```python3
>>> import torch_spline_conv
_version
_basis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".conda/envs/test39/lib/python3.9/site-packages/torch_spline_conv/__init__.py", line 12, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File ".conda/envs/test39/lib/python3.9/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File ".conda/envs/test39/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by .conda/envs/test39/lib/python3.9/site-packages/torch_spline_conv/_basis_cuda.so)
```
Meaning that the culprit is `_basis_cuda`, as also mentioned in the last line of the error. 
Further examination using `diff` between the recompiled (working) package in the `pytorch` conda environment and the original one the `test39` environment produced the following output:
```console
❯ diff -qr envs/test39/lib/python3.9/site-packages/torch_spline_conv envs/pytorch/lib/python3.9/site-packages/torch_spline_conv/
Files envs/test39/lib/python3.9/site-packages/torch_spline_conv/_basis_cpu.so and envs/pytorch/lib/python3.9/site-packages/torch_spline_conv/_basis_cpu.so differ
Files envs/test39/lib/python3.9/site-packages/torch_spline_conv/_basis_cuda.so and envs/pytorch/lib/python3.9/site-packages/torch_spline_conv/_basis_cuda.so differ
Files envs/test39/lib/python3.9/site-packages/torch_spline_conv/__pycache__/basis.cpython-39.pyc and envs/pytorch/lib/python3.9/site-packages/torch_spline_conv/__pycache__/basis.cpython-39.pyc differ
Files envs/test39/lib/python3.9/site-packages/torch_spline_conv/__pycache__/conv.cpython-39.pyc and envs/pytorch/lib/python3.9/site-packages/torch_spline_conv/__pycache__/conv.cpython-39.pyc differ
Files envs/test39/lib/python3.9/site-packages/torch_spline_conv/__pycache__/__init__.cpython-39.pyc and envs/pytorch/lib/python3.9/site-packages/torch_spline_conv/__pycache__/__init__.cpython-39.pyc differ
Files envs/test39/lib/python3.9/site-packages/torch_spline_conv/__pycache__/weighting.cpython-39.pyc and envs/pytorch/lib/python3.9/site-packages/torch_spline_conv/__pycache__/weighting.cpython-39.pyc differ
Files envs/test39/lib/python3.9/site-packages/torch_spline_conv/_version_cpu.so and envs/pytorch/lib/python3.9/site-packages/torch_spline_conv/_version_cpu.so differ
Files envs/test39/lib/python3.9/site-packages/torch_spline_conv/_version_cuda.so and envs/pytorch/lib/python3.9/site-packages/torch_spline_conv/_version_cuda.so differ
Files envs/test39/lib/python3.9/site-packages/torch_spline_conv/_weighting_cpu.so and envs/pytorch/lib/python3.9/site-packages/torch_spline_conv/_weighting_cpu.so differ
Files envs/test39/lib/python3.9/site-packages/torch_spline_conv/_weighting_cuda.so and envs/pytorch/lib/python3.9/site-packages/torch_spline_conv/_weighting_cuda.so differ
```
I don't know enough about the subject to make wild speculations, but could it be possible that the provided wheels were compiled in a different environment than the one they're supposed to work in?

**Comment by rusty1s** [comment] 2021-06-24 11:06
I'm sadly still not able to reproduce this issue on three different Ubuntu machines. Can you show me the output of running `ldd --version`?

**Comment by saiden89** [comment] 2021-06-24 11:09
```console
❯ ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

```

**Comment by rusty1s** [comment] 2021-06-24 12:00
I see. I'm seeing if I can go back to building via `ubuntu1604` and let you know.

**Comment by rusty1s** [comment] 2021-06-24 12:39
Updated the wheels. Please try again :)

**Comment by saiden89** [comment] 2021-06-24 13:27
Unfortunately, it doesn't... sorry. I've also created a new conda env from scratch and doing `pip cache purge` :cry:

**Comment by saiden89** [comment] 2021-06-24 13:37
It looks the same to me
```python3
❯ python
Python 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:32:32) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_spline_conv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".conda/envs/spline/lib/python3.9/site-packages/torch_spline_conv/__init__.py", line 11, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File ".conda/envs/spline/lib/python3.9/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File ".conda/envs/spline/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by .conda/envs/spline/lib/python3.9/site-packages/torch_spline_conv/_basis_cuda.so)
```

**Comment by rusty1s** [comment] 2021-06-24 19:29
Can you try to install via:
```
pip uninstall torch-spline-conv
pip install https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.9.0%2Bcu102/torch_spline_conv-1.2.1-cp39-cp39-linux_x86_64.whl
```

**Comment by saiden89** [comment] 2021-06-24 19:35
That did it, now it works :smile:. What was the issue?

**Comment by rusty1s** [comment] 2021-06-24 19:50
Should work just fine with `-f` as well, we just need to wait a few hours till CloudFront does not longer cache the old version.

**Comment by rusty1s** [comment] 2021-06-25 06:24
I'm closing this for now. Please feel free to re-open if you think this issue is not resolved yet.

**Closed by rusty1s** 2021-06-25 06:24 UTC

**Comment by hossam-zaki** [comment] 2021-11-29 06:16
Hello! I'm currently getting the same issue. I'm on torch version 1.10.0, pytorch-geometric 2.02, and cuda version 11.3. Here are the commands I ran
```
pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

pip3 install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
```

Then, I try importing, and it doesn't work... Any help would be great

**Comment by rusty1s** [comment] 2021-11-29 09:11
GLIBC=2.27 is now required as GitHub Actions no longer provide support for `ubuntu1604`.

**Comment by chrisyeh96** [comment] 2022-02-10 22:44
I'm also still having the same issue: `OSError: /lib64/libm.so.6: version 'GLIBC_2.27' not found`. I have installed `torch_geometric` via conda.

Here are the relevant lines from the output of `conda list`
```
# Name                    Version         Build                         Channel
cudatoolkit               10.2.89         h8f6ccaa_10                   conda-forge
pyg                       2.0.3           py39_torch_1.10.0_cu102       pyg
python                    3.9.10          h85951f9_2_cpython            conda-forge
pytorch                   1.10.0          py3.9_cuda10.2_cudnn7.6.5_0   pytorch
pytorch-cluster           1.5.9           py39_torch_1.10.0_cu102       pyg
pytorch-mutex             1.0             cuda                          pytorch
pytorch-scatter           2.0.9           py39_torch_1.10.0_cu102       pyg
pytorch-sparse            0.6.12          py39_torch_1.10.0_cu102       pyg
pytorch-spline-conv       1.2.1           py39_torch_1.10.0_cu102       pyg
```

I tried `conda install -c conda-forge glib` but that didn't help.

Also, I'm not sure what @rusty1s means by
> GLIBC=2.27 is now required as GitHub Actions no longer provide support for `ubuntu1604`.

Could you please elaborate on what that means for users of PyTorch Geometric?

**Comment by rusty1s** [comment] 2022-02-11 08:23
We will use GitHub Actions to build our wheels. For linux, this means that we make use of `ubuntu1804` which comes with `GLIBC_2.27` by default. As you pointed out in https://github.com/pyg-team/pytorch_geometric/issues/3477#issuecomment-1035620542, we may can resolve this issue by installing `conda` and install an earlier version of `glib`.

**Comment by hnisonoff** [comment] 2022-03-04 00:16
I am still having this issue. 
I tried building with `pip install torch-spline-conv` but this gave me a different error:


```
>>> import torch_spline_conv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/workspace/nisonoff/anaconda3/envs/pytorch_v3/lib/python3.9/site-packages/torch_spline_conv/__init__.py", line 11, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'
```

Do you have any advice @rusty1s ?

**Comment by hnisonoff** [comment] 2022-03-04 19:08
Actually I was able to pip install this successfully once I loaded the right cuda environment variables. Thanks!

**Comment by plutonium-239** [comment] 2022-05-27 18:50
@hnisonoff can you please describe what cuda environment variables you changed to get it working?
